from django import forms

lang_choice = (
    ('af', 'Afrikaans'),
    ('al', 'Albanian'),
    ('ar', 'Arabic'),
    ('az', 'Azerbaijani'),
    ('bg', 'Bulgarian'),
    ('ca', 'Catalan'),
    ('cz', 'Czech'),
    ('da', 'Danish'),
    ('de', 'German'),
    ('el', 'Greek'),
    ('en', 'English'),
    ('eu', 'Basque'),
    ('fa', 'Persian'),
    ('fa', 'Farsi'),
    ('fi', 'Finnish'),
    ('fr', 'French'),
    ('gl', 'Galician'),
    ('he', 'Hebrew'),
    ('hi', 'Hindi'),
    ('hr', 'Croatian'),
    ('hu', 'Hungarian'),
    ('id', 'Indonesian'),
    ('it', 'Italian'),
    ('ja', 'Japanese'),
    ('kr', 'Korean'),
    ('la', 'Latvian'),
    ('lt', 'Lithuanian'),
    ('mk', 'Macedonian'),
    ('no', 'Norwegian'),
    ('nl', 'Dutch'),
    ('pl', 'Polish'),
    ('pt', 'Portuguese'),
    ('pt_br', 'Português'),
    ('ro', 'Romanian'),
    ('ru', 'Russian'),
    ('sv', 'Swedish'),
    ('sk', 'Slovak'),
    ('sl', 'Slovenian'),
    ('es', 'Spanish'),
    ('sr', 'Serbian'),
    ('th', 'Thai'),
    ('tr', 'Turkish'),
    ('ua', 'Ukrainian'),
    ('vi', 'Vietnamese'),
    ('zh_tw', 'Chinese'),
    ('zu', 'Zulu'),
)

class WeatherForm(forms.Form):
    city = forms.CharField(max_length=200, widget=forms.TextInput(attrs={'placeholder': 'City', 'class': 'city_input'}))
    language_choice = forms.ChoiceField(choices=lang_choice)