# Generated by Django 4.1.4 on 2022-12-23 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Weather',
        ),
    ]
